set(CTEST_CUSTOM_TESTS_IGNORE 
build/_deps/systemclanguage-src/examples/sysc/2.1/dpipe/dpipe
build/_deps/systemclanguage-src/examples/sysc/2.1/forkjoin/forkjoin
build/_deps/systemclanguage-src/examples/sysc/2.1/reset_signal_is/reset_signal_is
build/_deps/systemclanguage-src/examples/sysc/2.1/sc_export/sc_export
build/_deps/systemclanguage-src/examples/sysc/2.1/sc_report/sc_report
build/_deps/systemclanguage-src/examples/sysc/2.1/scx_barrier/scx_barrier
build/_deps/systemclanguage-src/examples/sysc/2.1/scx_mutex_w_policy/scx_mutex_w_policy
build/_deps/systemclanguage-src/examples/sysc/2.1/specialized_signals/specialized_signals
build/_deps/systemclanguage-src/examples/sysc/2.3/sc_rvd/sc_rvd
build/_deps/systemclanguage-src/examples/sysc/2.3/sc_ttd/sc_ttd
build/_deps/systemclanguage-src/examples/sysc/2.3/simple_async/simple_async
build/_deps/systemclanguage-src/examples/sysc/fft/fft_flpt/fft_flpt
build/_deps/systemclanguage-src/examples/sysc/fft/fft_fxpt/fft_fxpt
build/_deps/systemclanguage-src/examples/sysc/fir/fir
build/_deps/systemclanguage-src/examples/sysc/fir/fir_rtl
build/_deps/systemclanguage-src/examples/sysc/pipe/pipe
build/_deps/systemclanguage-src/examples/sysc/pkt_switch/pkt_switch
build/_deps/systemclanguage-src/examples/sysc/risc_cpu/risc_cpu
build/_deps/systemclanguage-src/examples/sysc/rsa/rsa
build/_deps/systemclanguage-src/examples/sysc/simple_bus/simple_bus
build/_deps/systemclanguage-src/examples/sysc/simple_fifo/simple_fifo
build/_deps/systemclanguage-src/examples/sysc/simple_perf/simple_perf
build/_deps/systemclanguage-src/examples/tlm/at_1_phase/at_1_phase
build/_deps/systemclanguage-src/examples/tlm/at_2_phase/at_2_phase
build/_deps/systemclanguage-src/examples/tlm/at_4_phase/at_4_phase
build/_deps/systemclanguage-src/examples/tlm/at_extension_optional/at_extension_optional
build/_deps/systemclanguage-src/examples/tlm/at_mixed_targets/at_mixed_targets
build/_deps/systemclanguage-src/examples/tlm/at_ooo/at_ooo
build/_deps/systemclanguage-src/examples/tlm/lt/lt
build/_deps/systemclanguage-src/examples/tlm/lt_dmi/lt_dmi
build/_deps/systemclanguage-src/examples/tlm/lt_extension_mandatory/lt_extension_mandatory
build/_deps/systemclanguage-src/examples/tlm/lt_mixed_endian/lt_mixed_endian
build/_deps/systemclanguage-src/examples/tlm/lt_temporal_decouple/lt_temporal_decouple
)